#!/bin/bash
echo "🔐 CHECKING POSTGRESQL AUTHENTICATION"
echo "====================================="

echo ""
echo "1️⃣ Current PostgreSQL connection methods:"
sudo cat /etc/postgresql/*/main/pg_hba.conf 2>/dev/null | grep -E "^local|^host" | head -10 || \
echo "Check: sudo nano /etc/postgresql/*/main/pg_hba.conf"

echo ""
echo "2️⃣ Options to fix:"
echo ""
echo "OPTION A: Use password authentication (RECOMMENDED)"
echo "---------------------------------------------------"
echo "Update your .env.working with password:"
echo "  export DATABASE_URL=\"postgresql://saleh:YOUR_PASSWORD@localhost/passenger_impact_prod\""
echo ""
echo "OPTION B: Allow passwordless local connections"
echo "---------------------------------------------"
echo "Edit pg_hba.conf and change:"
echo "  local   all             all                                     peer"
echo "  TO:"
echo "  local   all             all                                     trust"
echo ""
echo "OPTION C: Create .pgpass file"
echo "----------------------------"
echo "Create ~/.pgpass with:"
echo "  localhost:5432:passenger_impact_prod:saleh:YOUR_PASSWORD"
echo "  chmod 600 ~/.pgpass"
