#!/bin/bash
echo "🔑 GETTING VALID STRIPE TEST KEY"
echo "================================"

echo ""
echo "To get a valid Stripe test API key:"
echo ""
echo "1. Go to: https://dashboard.stripe.com/test/apikeys"
echo "2. Copy the 'Secret key' (starts with 'sk_test_')"
echo "3. Update .env.working:"
echo ""
echo "   export STRIPE_SECRET_KEY=\"sk_test_REDACTED_valid_key_here\""
echo ""
echo "4. Also check:"
echo "   - Your Stripe account is in TEST mode (not LIVE)"
echo "   - The key is from the correct environment"
echo "   - No extra spaces or quotes in the key"
echo ""
echo "Example valid test key format:"
echo "   sk_test_REDACTED"
echo ""
echo "Current .env.working contents:"
echo "=============================="
cat .env.working | grep -E "(STRIPE|DATABASE|COMPANY|API_KEY)"
