#!/bin/bash
echo "🪝 SETTING UP STRIPE WEBHOOKS"
echo "=============================="

echo ""
echo "1️⃣ Go to Stripe Dashboard:"
echo "   https://dashboard.stripe.com/test/webhooks"
echo ""
echo "2️⃣ Click 'Add endpoint':"
echo "   URL: http://127.0.0.1:8080/enterprise/billing/webhook"
echo ""
echo "3️⃣ Select events:"
echo "   • checkout.session.completed"
echo "   • customer.subscription.created"
echo "   • customer.subscription.updated"
echo "   • invoice.payment_succeeded"
echo ""
echo "4️⃣ Copy the 'Signing secret' (starts with 'whsec_')"
echo ""
echo "5️⃣ Update .env.working:"
echo "   export STRIPE_WEBHOOK_SECRET='whsec_REDACTED_secret_here'"
echo ""
echo "6️⃣ Restart server:"
echo "   pkill -f 'uvicorn.*127.0.0.1.*8080'"
echo "   source .env.working"
echo "   export PYTHONPATH=\"\$PWD/src\""
echo "   uvicorn pie.api.app:app --host 127.0.0.1 --port 8080"
echo ""
echo "📝 For testing without real webhooks, use manual update below:"
