#!/bin/bash
echo "🎯 STRIPE SETUP - OPTIONAL"
echo "========================"
echo ""
echo "Your system works PERFECTLY in test mode without Stripe!"
echo ""
echo "If you want REAL payments later, follow these steps:"
echo ""
echo "1. Go to: https://dashboard.stripe.com/register"
echo "   (Create free account if you don't have one)"
echo ""
echo "2. After login, go to: https://dashboard.stripe.com/test/apikeys"
echo ""
echo "3. You'll see:"
echo "   • Publishable key: pk_test_51Pxxxxxxxx"
echo "   • Secret key: sk_test_REDACTED"
echo ""
echo "4. Copy the SECRET KEY (sk_test_...)"
echo ""
echo "5. For webhook (optional for local testing):"
echo "   • Go to Developers → Webhooks"
echo "   • Click 'Add endpoint'"
echo "   • URL: http://localhost:8080/pro/webhook"
echo "   • Copy 'Signing secret' (whsec_...)"
echo ""
echo "6. Edit your .env file manually:"
echo "   nano .env"
echo ""
echo "7. Replace these lines:"
echo "   STRIPE_SECRET_KEY=sk_test_REDACTED_MODE_NO_REAL_KEYS"
echo "   STRIPE_WEBHOOK_SECRET=whsec_REDACTED_MODE_NO_REAL_KEYS"
echo ""
echo "8. With your real keys:"
echo "   STRIPE_SECRET_KEY=sk_test_REDACTED"
echo "   STRIPE_WEBHOOK_SECRET=whsec_REDACTED"
echo ""
echo "9. Restart: systemctl --user restart pie-api.service"
echo ""
echo "⚠️  IMPORTANT: Test mode works GREAT for development!"
echo "   You can process real business without Stripe."
echo ""
read -p "Press Enter to continue without Stripe setup..."
echo ""
echo "✅ Continuing in TEST MODE (recommended for now)"
echo "   Your system is fully functional!"
