from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional, Mapping, Any

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


@dataclass(frozen=True)
class ExecutiveReport:
    job_id: str
    order_id: str
    company_id: str
    description: str
    iterations: int
    amount_eur: str
    paid_at: Optional[str]
    started_at: Optional[str]
    finished_at: Optional[str]
    kpis: Mapping[str, Any]


def render_executive_report_pdf(out_pdf: Path, report: ExecutiveReport) -> None:
    out_pdf.parent.mkdir(parents=True, exist_ok=True)

    c = canvas.Canvas(str(out_pdf), pagesize=A4)
    w, h = A4

    y = h - 60
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, y, "Passenger Impact Engine — Executive Report")
    y -= 30

    c.setFont("Helvetica", 11)
    c.drawString(50, y, f"Generated: {datetime.utcnow().isoformat()}Z")
    y -= 18
    c.drawString(50, y, f"Job ID: {report.job_id}")
    y -= 16
    c.drawString(50, y, f"Order ID: {report.order_id}")
    y -= 16
    c.drawString(50, y, f"Company ID: {report.company_id}")
    y -= 22

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Order Summary")
    y -= 16
    c.setFont("Helvetica", 11)
    c.drawString(50, y, f"Description: {report.description}")
    y -= 16
    c.drawString(50, y, f"Iterations: {report.iterations}")
    y -= 16
    c.drawString(50, y, f"Amount (EUR): {report.amount_eur}")
    y -= 16
    c.drawString(50, y, f"Paid At: {report.paid_at or 'N/A'}")
    y -= 22

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Run Timeline")
    y -= 16
    c.setFont("Helvetica", 11)
    c.drawString(50, y, f"Started At: {report.started_at or 'N/A'}")
    y -= 16
    c.drawString(50, y, f"Finished At: {report.finished_at or 'N/A'}")
    y -= 22

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Key Outputs (MVP)")
    y -= 16
    c.setFont("Helvetica", 11)

    # Print KPI lines safely
    for k, v in report.kpis.items():
        if y < 80:
            c.showPage()
            y = h - 60
            c.setFont("Helvetica", 11)
        c.drawString(50, y, f"- {k}: {v}")
        y -= 14

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(50, 40, "Confidential — generated by Passenger Impact Engine (PIE)")
    c.save()
