from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import pandas as pd


@dataclass(frozen=True)
class DashboardPaths:
    index_html: Path
    assets_dir: Path


def _safe_read_json(path: Path) -> dict:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _require(path: Path, msg: str) -> None:
    if not path.exists():
        raise FileNotFoundError(f"{msg}: {path}")


def _write_html(out_html: Path, title: str, body: str) -> None:
    out_html.write_text(
        f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>{title}</title>
<style>
  :root {{
    --bg: #0b0f17;
    --card: #121a27;
    --text: #e8eefc;
    --muted: #a9b4cc;
    --line: rgba(255,255,255,.08);
    --accent: #6aa6ff;
  }}
  body {{
    margin: 0;
    font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial;
    background: var(--bg);
    color: var(--text);
  }}
  .wrap {{
    max-width: 1100px;
    margin: 0 auto;
    padding: 28px 18px 60px;
  }}
  h1 {{
    font-size: 28px;
    margin: 0 0 6px;
  }}
  .sub {{
    color: var(--muted);
    margin-bottom: 22px;
  }}
  .grid {{
    display: grid;
    grid-template-columns: repeat(12, 1fr);
    gap: 14px;
  }}
  .card {{
    background: var(--card);
    border: 1px solid var(--line);
    border-radius: 14px;
    padding: 14px;
  }}
  .span-12 {{ grid-column: span 12; }}
  .span-6 {{ grid-column: span 6; }}
  .span-4 {{ grid-column: span 4; }}
  .span-8 {{ grid-column: span 8; }}
  .kpi {{
    font-size: 13px;
    color: var(--muted);
  }}
  .kpi strong {{
    display: block;
    font-size: 22px;
    color: var(--text);
    margin-top: 4px;
  }}
  table {{
    width: 100%;
    border-collapse: collapse;
    font-size: 13px;
  }}
  th, td {{
    text-align: left;
    padding: 10px 8px;
    border-bottom: 1px solid var(--line);
    vertical-align: top;
  }}
  th {{
    color: var(--muted);
    font-weight: 600;
  }}
  .pill {{
    display: inline-block;
    padding: 2px 8px;
    border-radius: 999px;
    background: rgba(106,166,255,.12);
    color: var(--accent);
    border: 1px solid rgba(106,166,255,.25);
    font-size: 12px;
  }}
  img {{
    max-width: 100%;
    border-radius: 10px;
    border: 1px solid var(--line);
  }}
  .muted {{
    color: var(--muted);
  }}
  .footer {{
    margin-top: 18px;
    color: var(--muted);
    font-size: 12px;
  }}
  @media (max-width: 900px) {{
    .span-6, .span-4, .span-8 {{ grid-column: span 12; }}
  }}
</style>
</head>
<body>
<div class="wrap">
{body}
<div class="footer">Generated by Passenger Impact Engine — dashboard</div>
</div>
</body>
</html>
""",
        encoding="utf-8",
    )


def build_dashboard(out_dir: str, top: int = 20) -> DashboardPaths:
    out = Path(out_dir)
    dash = out / "dashboard"
    assets = dash / "assets"
    assets.mkdir(parents=True, exist_ok=True)

    run_json = out / "run.json"
    stats_json = out / "stats.json"
    groups_csv = out / "stats_groups.csv"
    top_csv = out / "stats_top_passengers.csv"

    _require(run_json, "Missing run metadata. Run simulate first")
    _require(stats_json, "Missing stats.json. Run: pie stats")
    _require(groups_csv, "Missing stats_groups.csv. Run: pie stats")
    _require(top_csv, "Missing stats_top_passengers.csv. Run: pie stats")

    run = _safe_read_json(run_json)
    stats = _safe_read_json(stats_json)

    groups = pd.read_csv(groups_csv)
    top_df = pd.read_csv(top_csv).head(top)

    # Make charts (matplotlib optional; we import only when used)
    chart_paths = _make_charts(assets, groups, top_df)

    # Render tables
    groups_html = _df_to_html(groups)
    top_html = _df_to_html(top_df)

    # KPIs
    mean_total = run.get("mean_total_cost", None)
    p95_total = run.get("p95_total_cost", None)
    cvar95_total = run.get("cvar95_total_cost", None)
    run_id = run.get("run_id", "unknown")

    by = stats.get("by", "unknown")
    metric = stats.get("metric", "unknown")

    body = f"""
<h1>Passenger Impact Engine — Dashboard</h1>
<div class="sub">
  Run: <span class="pill">{run_id}</span>
  &nbsp;&nbsp; Grouping: <span class="pill">{by}</span>
  &nbsp;&nbsp; Metric: <span class="pill">{metric}</span>
</div>

<div class="grid">
  <div class="card span-4"><div class="kpi">Mean total cost (EUR)<strong>{_fmt(mean_total)}</strong></div></div>
  <div class="card span-4"><div class="kpi">P95 total cost (EUR)<strong>{_fmt(p95_total)}</strong></div></div>
  <div class="card span-4"><div class="kpi">CVaR95 total cost (EUR)<strong>{_fmt(cvar95_total)}</strong></div></div>

  <div class="card span-12">
    <h3 style="margin:0 0 10px;">Charts</h3>
    <div class="grid">
      <div class="span-6">{_img(chart_paths.get("mean_by_group"), "Mean cost by group")}</div>
      <div class="span-6">{_img(chart_paths.get("p95_by_group"), "P95 cost by group")}</div>
      <div class="span-12">{_img(chart_paths.get("top_passengers"), "Top passengers by score")}</div>
      <div class="span-12">{_img(chart_paths.get("components"), "Cost components (sum)")}</div>
    </div>
  </div>

  <div class="card span-12">
    <h3 style="margin:0 0 10px;">Group statistics</h3>
    <div class="muted" style="margin-bottom:10px;">Source: stats_groups.csv</div>
    {groups_html}
  </div>

  <div class="card span-12">
    <h3 style="margin:0 0 10px;">Top passengers</h3>
    <div class="muted" style="margin-bottom:10px;">Source: stats_top_passengers.csv</div>
    {top_html}
  </div>
</div>
"""

    index = dash / "index.html"
    _write_html(index, "PIE Dashboard", body)

    return DashboardPaths(index_html=index, assets_dir=assets)


def _fmt(x) -> str:
    try:
        if x is None:
            return "—"
        return f"{float(x):,.2f}"
    except Exception:
        return "—"


def _df_to_html(df: pd.DataFrame) -> str:
    # make it compact & readable
    return df.to_html(index=False, escape=True)


def _img(path: Path | None, alt: str) -> str:
    if path is None:
        return f"<div class='muted'>No chart: {alt}</div>"
    rel = f"assets/{path.name}"
    return f"<img src='{rel}' alt='{alt}'/>"


def _make_charts(assets: Path, groups: pd.DataFrame, top_df: pd.DataFrame) -> dict[str, Path]:
    import matplotlib.pyplot as plt

    out: dict[str, Path] = {}

    # Mean by group
    if "group" in groups.columns and "mean_total_cost_eur" in groups.columns:
        p = assets / "mean_by_group.png"
        _bar(
            x=groups["group"].astype(str),
            y=groups["mean_total_cost_eur"].astype(float),
            title="Mean total cost by group",
            xlabel="Group",
            ylabel="Mean total cost (EUR)",
            out_path=p,
            plt=plt,
        )
        out["mean_by_group"] = p

    # P95 by group
    if "group" in groups.columns and "p95_total_cost_eur" in groups.columns:
        p = assets / "p95_by_group.png"
        _bar(
            x=groups["group"].astype(str),
            y=groups["p95_total_cost_eur"].astype(float),
            title="P95 total cost by group",
            xlabel="Group",
            ylabel="P95 total cost (EUR)",
            out_path=p,
            plt=plt,
        )
        out["p95_by_group"] = p

    # Top passengers by score
    if "passenger_id" in top_df.columns and "score" in top_df.columns:
        p = assets / "top_passengers.png"
        _bar(
            x=top_df["passenger_id"].astype(str),
            y=top_df["score"].astype(float),
            title="Top passengers by score",
            xlabel="Passenger",
            ylabel="Score",
            out_path=p,
            plt=plt,
            rotate_xticks=True,
        )
        out["top_passengers"] = p

    # Components (sum) - from groups table
    comp_cols = [
        ("sum_cash_comp_eur", "Cash"),
        ("sum_care_cost_eur", "Care"),
        ("sum_refund_cost_eur", "Refund"),
        ("sum_rebooking_cost_eur", "Rebook"),
    ]
    if all(c in groups.columns for c, _ in comp_cols):
        p = assets / "components.png"
        vals = [float(groups[c].sum()) for c, _ in comp_cols]
        labels = [name for _, name in comp_cols]

        plt.figure()
        plt.bar(labels, vals)
        plt.title("Total cost components (sum over groups)")
        plt.ylabel("EUR")
        plt.tight_layout()
        plt.savefig(p, dpi=140)
        plt.close()

        out["components"] = p

    return out


def _bar(
    *,
    x,
    y,
    title: str,
    xlabel: str,
    ylabel: str,
    out_path: Path,
    plt,
    rotate_xticks: bool = False,
) -> None:
    plt.figure()
    plt.bar(x, y)
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    if rotate_xticks:
        plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.savefig(out_path, dpi=140)
    plt.close()
